player-addcoin: "§e§l☞ You added Coin for {player} {coin} Coin"
player-receive-addcoin: "§c§l☞ You have received {coin} Coin"
seecoin: "§e§l☞ Player {player} having {coin} Coin"
mycoin: "§e§l☞ You have {coin} Coin"
player-setcoin: "§e§l☞ You have set {coin} Coin for {player}"
player-receive-setcoin: "§c§l☞ Your Coin Number Has Been Set to {coin} Coin"
paycoin-yourself: "§c§l☞ You can't paycoin for yourself"
player-paycoin: "§e§l☞ You paid {coin} Coin for {player}"
player-receive-paycoin: "§c§l☞ You have received {coin} Coin from {player}"
no-player: "§a§l☞ Player Not Found"
player-takecoin: "§e§l☞ You took {coin} Coin from player {player}"
player-receive-takecoin: "§c§l☞ You have been taken away {coin} Coin"